services:
  - type: web
    name: finance-tracker-backend
    env: python
    region: oregon
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn main:app -c gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
