services:
  - type: web
    name: finance-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: pserv
    name: finance-tracker-db
    env: postgresql
    plan: free
    databaseName: finance_db
    user: finance_user
